--delete from __EFMigrationsHistory
--delete from AspNetRoleClaims
--delete from AspNetRoles
--delete from AspNetUserClaims
--delete from AspNetUserLogins
--delete from AspNetUserRoles
--delete from AspNetUsers
--delete from AspNetUserTokens
delete from cmi_comment_from_learner
delete from cmi_comment_from_lms
delete from cmi_core
delete from cmi_data
delete from cmi_interactions
delete from cmi_interactions_correct_responses
delete from cmi_interactions_objectives
delete from cmi_objectives
delete from cmi_student_preferences
delete from SCORM_Course
delete from [session]
delete from User_Module
--truncate TABLE SCORM_Course