delete from cmi_comment_from_learner
delete from cmi_comment_from_lms
delete from [session]
delete from cmi_core
delete from cmi_data
delete from cmi_interactions_correct_responses
delete from cmi_interactions_objectives
delete from cmi_interactions
delete from cmi_objectives
delete from User_Module
delete from SCORM_Course
delete from cmi_student_preferences