select 'cmi_comment_from_learner',* from cmi_comment_from_learner
select 'cmi_comment_from_lms',* from cmi_comment_from_lms
select 'cmi_core',* from cmi_core
select 'cmi_data',* from cmi_data
select 'cmi_interactions',* from cmi_interactions
select 'cmi_interactions_correct_responses',* from cmi_interactions_correct_responses
select 'cmi_interactions_objectives',* from cmi_interactions_objectives
select 'cmi_objectives',* from cmi_objectives
select 'cmi_student_preferences',* from cmi_student_preferences
select 'SCORM_Course',* from SCORM_Course
select 'session',* from [session]
select 'User_Module',* from User_Module